### ISSUE TITLE
Not work on mac: "Verification failed, wrong pin?" 

### ISSUE THREAD

**Issue by zeleznypa** [a-dma/yubitouch#6]
When I tried to run this script, it will every time fail with "Verification failed, wrong pin?" message

After a while, I have found that PIN property for real pin "12345679" contains asci value "2d6e2031323334353637390a" that is for "-n 12345679". After delete -n operator on line 97, everything works well.

https://github.com/a-dma/yubitouch/blob/2b5f0e6cab7c8c2f17e91485ca74fd49e4bbda93/yubitouch.sh#L97

**Comment by a-dma** [comment]
I assume that's because you're using a POSIX echo. You should be able to work around it by using `printf` instead:

```
PIN=$(printf "$PIN" | ascii_to_hex | tr -d '\n') 
```

If that works I'll update the script.

EDIT: is this because of the recent changes of default shell in macOS?

**Comment by zeleznypa** [comment]
For numeric PIN it works well. 👍 Thanks much. 🙇
