### ISSUE TITLE
Improve documentation for non-numeric passwords

### ISSUE THREAD

**Issue by zeleznypa** [a-dma/yubitouch#7]
Because the command is interpreted by the bash command line before the execution, there can be an issue with a password that contains characters like $.

It will be useful to improve a readme file here: https://github.com/a-dma/yubitouch/blame/master/README.org#L22

change it please with:

```
./yubitouch.sh {sig|aut|dec} {off|on|fix} '[admin_pin]'
```

It will work also with numeric passwords but prevent the issue described above...

**Comment by a-dma** [comment]
That line is trying to show the grammar that the command accepts, I don't think adding quotes around the argument makes sense. I can update the README, but I think escaping should be on the userm depending on what they use to invoke the script.
