### ISSUE TITLE
Avoid errors when commands don't exist

### ISSUE THREAD

**Issue by gatheall** [a-dma/yubitouch#8]
I discovered your script today and successfully used it to require touch for my Yubikeys. Thanks!

One minor issue I saw when running it was a message from _which_ telling me that I don't have _xxd_ on my system; eg, 

`which: no xxd in (/usr/sbin:/usr/bin:/sbin:/bin)`

Is it worth redirecting stderr to /dev/null each time calling that in the script?

**Comment by a-dma** [comment]
Hey, I'm glad that you found this useful.

Interesting problem there, my `which` is nice and quiet and doesn't seem to complain. What OS and shell are you running? BSD?

Using `which` is generally not the best choice, but for a different set of reasons. Does replacing that with `command -v` make it better for you? If so I may update the script.

**Comment by gatheall** [comment]
> Interesting problem there, my `which` is nice and quiet and doesn't seem to complain. What OS and shell are you running? BSD?

This happens on Gentoo. bash is 5.0.16(1)-release, and the _which_ implementation is from https://carlowood.github.io/which/

> Using `which` is generally not the best choice, but for a different set of reasons. Does replacing that with `command -v` make it better for you? If so I may update the script.

That works for me; eg,

    theall@garlic:~>which xxd
    which: no xxd in (/usr/sbin:/usr/bin:/sbin:/bin)
    theall@garlic:~>command -v xxd

and 

    theall@garlic:~>which od
    /usr/bin/od
    theall@garlic:~>command -v od
    /usr/bin/od

**Comment by a-dma** [comment]
I see. I'm also using Bash I'm a few minors away. It must be the implementation of `which`.

I've been meaning to do away with that anyway, but never gotten around to. I'll push a small diff. Feedback would be appreciated if you have the time.

Thanks.

**Comment by gatheall** [comment]
> I see. I'm also using Bash I'm a few minors away. It must be the implementation of `which`.
> 
> I've been meaning to do away with that anyway, but never gotten around to. I'll push a small diff. Feedback would be appreciated if you have the time.

Thanks, the patch fixed the issue I had and looks good to me. [For what it's worth, though, PE is still defined using _which_.]

**Comment by a-dma** [comment]
Derp.

Thanks and thanks for testing.
